# Generated by Django 4.1.5 on 2023-01-10 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('tName', models.CharField(max_length=16)),
                ('profession', models.CharField(max_length=16)),
            ],
        ),
    ]
